name: Upload data

on:
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
          echo '{"train accuracy": 94.42, "test accuracy": 98.33, "train loss": 0.0029, "test loss": 0.3609}' > ./pr/best_record.json
      - uses: actions/upload-artifact@v3
        with:
          name: pr_artifact
          path: pr/
