name: Upload data

on:
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
          echo $PR_NUMBER
          echo '{"train accuracy": "94.42", "test accuracy": "98.33", "train loss": "0.0029", "test loss": "0.3609"}' > ./pr/best_record.json

      - name: 'Comment on PR'
        uses: actions/github-script@v6
        with:
          script: |
            let fs = require('fs');
            let issue_number = Number(fs.readFileSync('./pr/pr_number'));
            console.log(issue_number)
            let best_record = JSON.parse(fs.readFileSync('./pr/best_record.json'));
            console.log(best_record)
            const d = best_record
            const keys = Object.keys(d)

            let readme = `| Field | Type | Value |\n|-------|------|-------|\n`
            `

            keys.map((key) => {
              readme += `| ${key} | ${typeof d[key]} | ${d[key]} |\n `
            })
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: readme
            })
